#### Serial config ####
# CONFIG_SERIAL=y
# CONFIG_GPIO=y
# CONFIG_UART_CONSOLE=y
# CONFIG_UART_INTERRUPT_DRIVEN=y

CONFIG_SHELL_PRINTF_BUFF_SIZE=500
CONFIG_THREAD_STACK_INFO=y
CONFIG_STACK_SENTINEL=y
CONFIG_NET_TX_STACK_SIZE=2048
CONFIG_NET_RX_STACK_SIZE=2048
CONFIG_NET_MGMT_EVENT_QUEUE_SIZE=40
CONFIG_UART_NS16550_VARIANT_NS16750=n
CONFIG_PRINTK=y
CONFIG_GPIO=y
CONFIG_SERIAL=y
CONFIG_MODEM=y
CONFIG_NETWORKING=y
CONFIG_NET_SOCKETS=y
CONFIG_NET_IPV4=y
CONFIG_NET_IPV6=n

CONFIG_WIFI_LOG_LEVEL_DBG=y

CONFIG_NET_SHELL=y
CONFIG_NET_L2_WIFI_SHELL=y

CONFIG_WIFI=y
CONFIG_WIFI_ESP_AT=y
CONFIG_WIFI_ESP_AT_VERSION_1_7=y # clickboard is in 1.7.5 version