#### Serial config ####
CONFIG_SERIAL=y
CONFIG_GPIO=y
CONFIG_UART_CONSOLE=y
CONFIG_UART_INTERRUPT_DRIVEN=y




#### FS Section ####
CONFIG_FLASH=y
CONFIG_FILE_SYSTEM=y
CONFIG_FILE_SYSTEM_LITTLEFS=y
CONFIG_FLASH_MAP=y
CONFIG_MPU_ALLOW_FLASH_WRITE=y      # Implicitely declared with MCUBOOT


CONFIG_OSPI_FLASH_IS25WX=y
CONFIG_OSPI=y
CONFIG_USE_ALIF_HAL_OSPI=y